
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.3 EDK_MS3.70d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "sg_rgb_2d_fir_s6_plbw.h"

/*
* The configuration table for devices
*/

SG_RGB_2D_FIR_S6_PLBW_Config SG_RGB_2D_FIR_S6_PLBW_ConfigTable[] =
{
	{
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_XC_VERSION,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_XC_CREATE,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_XC_RELEASE,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_XC_OPEN,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_XC_CLOSE,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_XC_READ,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_XC_WRITE,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_XC_GET_SHMEM,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_MEMMAP_COEF_UPDATE,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_MEMMAP_COEF_UPDATE_N_BITS,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_MEMMAP_COEF_UPDATE_BIN_PT,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_MEMMAP_COEF_GAIN,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_MEMMAP_COEF_GAIN_N_BITS,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_MEMMAP_COEF_GAIN_BIN_PT,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_MEMMAP_COEF_BUFFER,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_MEMMAP_COEF_BUFFER_N_BITS,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_MEMMAP_COEF_BUFFER_BIN_PT,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_MEMMAP_COEF_BUFFER_DEPTH,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_DEVICE_ID,
		XPAR_SG_RGB_2D_FIR_S6_PLBW_0_BASEADDR
	}
};


