
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.3 EDK_MS3.70d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xvdma.h"

/*
* The configuration table for devices
*/

XVDma_Config XVDma_ConfigTable[] =
{
	{
		XPAR_VDMA_0_DEVICE_ID,
		XPAR_VDMA_0_BASEADDR,
		XPAR_VDMA_0_NUM_FSTORES
	},
	{
		XPAR_VDMA_1_DEVICE_ID,
		XPAR_VDMA_1_BASEADDR,
		XPAR_VDMA_1_NUM_FSTORES
	}
};


