
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.3 EDK_MS3.70d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "sg_gamma_s6_plbw.h"

/*
* The configuration table for devices
*/

SG_GAMMA_S6_PLBW_Config SG_GAMMA_S6_PLBW_ConfigTable[] =
{
	{
		XPAR_GAMMA_PLBW_0_XC_VERSION,
		XPAR_GAMMA_PLBW_0_XC_CREATE,
		XPAR_GAMMA_PLBW_0_XC_RELEASE,
		XPAR_GAMMA_PLBW_0_XC_OPEN,
		XPAR_GAMMA_PLBW_0_XC_CLOSE,
		XPAR_GAMMA_PLBW_0_XC_READ,
		XPAR_GAMMA_PLBW_0_XC_WRITE,
		XPAR_GAMMA_PLBW_0_XC_GET_SHMEM,
		XPAR_GAMMA_PLBW_0_MEMMAP_GAMMA_BUFFER,
		XPAR_GAMMA_PLBW_0_MEMMAP_GAMMA_BUFFER_N_BITS,
		XPAR_GAMMA_PLBW_0_MEMMAP_GAMMA_BUFFER_BIN_PT,
		XPAR_GAMMA_PLBW_0_MEMMAP_GAMMA_B,
		XPAR_GAMMA_PLBW_0_MEMMAP_GAMMA_B_N_BITS,
		XPAR_GAMMA_PLBW_0_MEMMAP_GAMMA_B_BIN_PT,
		XPAR_GAMMA_PLBW_0_MEMMAP_GAMMA_B_DEPTH,
		XPAR_GAMMA_PLBW_0_MEMMAP_GAMMA_G,
		XPAR_GAMMA_PLBW_0_MEMMAP_GAMMA_G_N_BITS,
		XPAR_GAMMA_PLBW_0_MEMMAP_GAMMA_G_BIN_PT,
		XPAR_GAMMA_PLBW_0_MEMMAP_GAMMA_G_DEPTH,
		XPAR_GAMMA_PLBW_0_MEMMAP_GAMMA_R,
		XPAR_GAMMA_PLBW_0_MEMMAP_GAMMA_R_N_BITS,
		XPAR_GAMMA_PLBW_0_MEMMAP_GAMMA_R_BIN_PT,
		XPAR_GAMMA_PLBW_0_MEMMAP_GAMMA_R_DEPTH,
		XPAR_GAMMA_PLBW_0_DEVICE_ID,
		XPAR_GAMMA_PLBW_0_BASEADDR
	}
};


