
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 3.00.a
 PARAMETER PROC_INSTANCE = microblaze_0
 PARAMETER STDIN = RS232_Uart
 PARAMETER STDOUT = RS232_Uart
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 1.13.a
 PARAMETER HW_INSTANCE = microblaze_0
 PARAMETER COMPILER = mb-gcc
 PARAMETER ARCHIVER = mb-ar
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = dlmb_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = ilmb_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = lmb_bram
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 1.14.a
 PARAMETER HW_INSTANCE = RS232_Uart
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 2.13.a
 PARAMETER HW_INSTANCE = LEDs_8Bit
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = mpmc
 PARAMETER DRIVER_VER = 4.01.a
 PARAMETER HW_INSTANCE = MPMC_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = clock_generator_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 1.14.a
 PARAMETER HW_INSTANCE = mdm_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = proc_sys_reset_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = vdma
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = vdma_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = vdma
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = vdma_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ivk_video_det
 PARAMETER DRIVER_VER = 2.01.a
 PARAMETER HW_INSTANCE = ivk_video_det_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ivk_video_gen
 PARAMETER DRIVER_VER = 2.01.a
 PARAMETER HW_INSTANCE = ivk_video_gen_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = iic
 PARAMETER DRIVER_VER = 1.16.a
 PARAMETER HW_INSTANCE = xps_iic_0
END

# BEGIN DRIVER
# PARAMETER DRIVER_NAME = iic
# PARAMETER DRIVER_VER = 1.16.a
# PARAMETER HW_INSTANCE = xps_iic_1
# END
BEGIN DRIVER
 PARAMETER DRIVER_NAME = sg_i2c_controller_s6_plbw
 PARAMETER DRIVER_VER = 1.01.a
 PARAMETER HW_INSTANCE = sg_i2c_controller_plbw_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = sg_cfa_s6_plbw
 PARAMETER DRIVER_VER = 3.01.c
 PARAMETER HW_INSTANCE = cfa_plbw_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = sg_gamma_s6_plbw
 PARAMETER DRIVER_VER = 3.01.c
 PARAMETER HW_INSTANCE = gamma_plbw_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = sg_rgb_2d_fir_s6_plbw
 PARAMETER DRIVER_VER = 3.01.c
 PARAMETER HW_INSTANCE = sg_rgb_2d_fir_s6_plbw_0
END


BEGIN LIBRARY
 PARAMETER LIBRARY_NAME = fmc_imageov_sw
 PARAMETER LIBRARY_VER = 1.02.b
 PARAMETER PROC_INSTANCE = microblaze_0
END

BEGIN LIBRARY
 PARAMETER LIBRARY_NAME = fmc_ipmi_sw
 PARAMETER LIBRARY_VER = 1.01.a
 PARAMETER PROC_INSTANCE = microblaze_0
END

BEGIN LIBRARY
 PARAMETER LIBRARY_NAME = fmc_iic_sw
 PARAMETER LIBRARY_VER = 1.03.a
 PARAMETER PROC_INSTANCE = microblaze_0
END

