
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.3 EDK_MS3.70d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "sg_cfa_s6_plbw.h"

/*
* The configuration table for devices
*/

SG_CFA_S6_PLBW_Config SG_CFA_S6_PLBW_ConfigTable[] =
{
	{
		XPAR_CFA_PLBW_0_XC_VERSION,
		XPAR_CFA_PLBW_0_XC_CREATE,
		XPAR_CFA_PLBW_0_XC_RELEASE,
		XPAR_CFA_PLBW_0_XC_OPEN,
		XPAR_CFA_PLBW_0_XC_CLOSE,
		XPAR_CFA_PLBW_0_XC_READ,
		XPAR_CFA_PLBW_0_XC_WRITE,
		XPAR_CFA_PLBW_0_XC_GET_SHMEM,
		XPAR_CFA_PLBW_0_MEMMAP_BAYER_CTRL,
		XPAR_CFA_PLBW_0_MEMMAP_BAYER_CTRL_N_BITS,
		XPAR_CFA_PLBW_0_MEMMAP_BAYER_CTRL_BIN_PT,
		XPAR_CFA_PLBW_0_DEVICE_ID,
		XPAR_CFA_PLBW_0_BASEADDR
	}
};


